### ISSUE TITLE
Password recovery not working

### ISSUE THREAD

**Issue by zaunders** [localfoodnodes/localfoodnodes#27] opened 2017-05-31 18:35 UTC
User gets bounced from resetting to loginpage and unable to login.

![image](https://cloud.githubusercontent.com/assets/6172443/26647757/a14c49c2-4640-11e7-933a-e3ff5b07195d.png)

**Comment by davidajnered** [comment] 2017-06-01 06:25
Fixed in https://github.com/localfoodnodes/localfoodnodes/commit/f00681de6ec362d447ecb18e65c7623758f3af1d. Problem caused by breaking change in Laravel 5.4 where Laravel now hashes the reset password token.

**Closed** 2017-06-01 06:26 UTC
Labels: bug
